-- MySQL Script generated by MySQL Workbench
-- 12/13/16 18:08:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema recordcollection
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recordcollection
-- -----------------------------------------------------
CREATE DATABASE `record_collection` DEFAULT CHARACTER SET utf8 ;
USE `record_collection` ;

-- -----------------------------------------------------
-- Table `recordcollection`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recordcollection`.`Genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recordcollection`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recordcollection`.`Album` (
  `album_num` INT NOT NULL AUTO_INCREMENT,
  `Albumcol` VARCHAR(45) NULL,
  `Genre_genre_id` INT NOT NULL,
  PRIMARY KEY (`album_num`),
  INDEX `fk_Album_Genre1_idx` (`Genre_genre_id` ASC),
  CONSTRAINT `fk_Album_Genre1`
    FOREIGN KEY (`Genre_genre_id`)
    REFERENCES `recordcollection`.`Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recordcollection`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recordcollection`.`Artist` (
  `artist_num` INT NOT NULL AUTO_INCREMENT,
  `artist_name` VARCHAR(100) NULL,
  `genre_id` INT NOT NULL,
  `Album_album_num` INT NOT NULL,
  `year_purchased` VARCHAR(4) NULL,
  PRIMARY KEY (`artist_num`, `Album_album_num`, `genre_id`),
  INDEX `genre_id_idx` (`genre_id` ASC),
  INDEX `fk_Artist_Album1_idx` (`Album_album_num` ASC),
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `recordcollection`.`Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_Album1`
    FOREIGN KEY (`Album_album_num`)
    REFERENCES `recordcollection`.`Album` (`album_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recordcollection`.`Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recordcollection`.`Label` (
  `label_num` INT NOT NULL AUTO_INCREMENT,
  `label_name` VARCHAR(100) NULL,
  `Album_album_num` INT NOT NULL,
  PRIMARY KEY (`label_num`),
  INDEX `fk_Label_Album1_idx` (`Album_album_num` ASC),
  CONSTRAINT `fk_Label_Album1`
    FOREIGN KEY (`Album_album_num`)
    REFERENCES `recordcollection`.`Album` (`album_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
